# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Durumu'),
        ),
    ]
