# Generated by Django 3.0.6 on 2020-06-04 11:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Projenin Adı')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='İçerik')),
                ('documentation', models.FileField(blank=True, null=True, upload_to='', verbose_name='Dökümantasyon')),
                ('lower_price', models.FloatField(default=0, verbose_name='Fiyat Alt Sınırı')),
                ('upper_price', models.FloatField(verbose_name='Fiyat Üst Sınırı')),
                ('deadline', models.DateTimeField(verbose_name='Proje Teslim Tarihi')),
                ('done', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Proje Sahibi')),
            ],
        ),
    ]
