# Generated by Django 3.0.3 on 2020-05-31 22:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Projenin Adı')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='İçerik')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Proje Sahibi')),
            ],
        ),
    ]
