# Generated by Django 3.0.3 on 2020-06-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200603_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(verbose_name='Proje Teslim Tarihi'),
        ),
    ]
