# Generated by Django 3.0.3 on 2020-06-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200603_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documentation',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Dökümantasyon'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lower_price',
            field=models.FloatField(default=0, verbose_name='Fiyat Alt Sınırı'),
        ),
    ]
