# Generated by Django 3.0.3 on 2020-06-02 23:25

import ckeditor.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('surname', models.CharField(max_length=150, verbose_name='Soyad')),
                ('register_date', models.DateTimeField(verbose_name='Kayıt Tarihi')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('cep_tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('experience', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tecrübe')),
                ('instructor_score', models.IntegerField(verbose_name='Eğitmenlik Puanı')),
                ('total_course_number', models.IntegerField(default=0, verbose_name='Şimdiye Kadar Verilen Dersler')),
                ('current_course_number', models.IntegerField(default=0, verbose_name='Güncel Ders Sayısı')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
            ],
        ),
    ]
