# Generated by Django 3.0.6 on 2020-06-05 06:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('surname', models.CharField(max_length=150, verbose_name='Soyad')),
                ('register_date', models.DateTimeField(editable=False, verbose_name='Kayıt Tarihi')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('cep_tel', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf')),
                ('experience', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tecrübe')),
                ('instructor_score', models.IntegerField(blank=True, null=True, verbose_name='Eğitmenlik Puanı')),
                ('total_course_number', models.IntegerField(default=0, verbose_name='Şimdiye Kadar Verilen Dersler')),
                ('current_course_number', models.IntegerField(default=0, verbose_name='Güncel Ders Sayısı')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Kullanıcı')),
            ],
        ),
    ]
